---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check that the path is available at the mountpoint
      ansible.builtin.stat:
        path: "{{ item }}"
      register: autofs_test_bind
      failed_when:
        - not autofs_test_bind.stat.exists
      loop:
        - /bind/mnt/mount
        - /bind/direct/mount
